#!/usr/bin/env node
// Compiles tokens/tokens.json into app/tokens.css.
//
//   npm run tokens        (also runs automatically before `dev` and `build`)
//
// tokens.json is a flat, DTCG-style file whose keys are the Figma variable
// names ("color/ink", "radius/md"). A key becomes a CSS custom property by
// swapping "/" for "-": color/ink -> --color-ink. Colour tokens carry a
// { light, dark } pair; the dark value is emitted under prefers-color-scheme.
//
// Groups that match a Tailwind v4 theme namespace (color, font, radius) are
// registered in @theme so they also generate utilities: bg-surface, text-ink,
// font-mono, rounded-md. Everything else is a plain variable on :root.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(root, "tokens/tokens.json");
const OUT = resolve(root, "app/tokens.css");
const THEME_GROUPS = new Set(["color", "font", "radius"]);

const tokens = JSON.parse(readFileSync(SRC, "utf8"));
const theme = [];
const plain = [];
const dark = [];

for (const [name, token] of Object.entries(tokens)) {
  if (name.startsWith("$")) continue; // file-level metadata such as $description
  const prop = `--${name.replaceAll("/", "-")}`;
  const value = token.$value;
  if (value === undefined) fail(name, "has no $value");

  if (isPlainObject(value) && "light" in value) {
    if (!("dark" in value)) fail(name, 'has a "light" value but no "dark" one');
    push(name, prop, css(name, value.light));
    dark.push(`${prop}: ${css(name, value.dark)};`);
  } else {
    push(name, prop, css(name, value));
  }
}

function push(name, prop, value) {
  const group = name.split("/")[0];
  (THEME_GROUPS.has(group) ? theme : plain).push(`${prop}: ${value};`);
}

/** Turns one DTCG value into CSS text. */
function css(name, value) {
  if (typeof value === "string") return value;
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map(quoteFamily).join(", ");
  if (isPlainObject(value) && "value" in value && "unit" in value) {
    return `${value.value}${value.unit}`;
  }
  return fail(name, `has an unsupported value ${JSON.stringify(value)}`);
}

function isPlainObject(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}

/** Font family names with spaces or punctuation need quotes in CSS. */
function quoteFamily(family) {
  return /^[a-zA-Z_-][\w-]*$/.test(family) || family.startsWith("var(")
    ? family
    : JSON.stringify(family);
}

function fail(name, message) {
  console.error(`tokens: "${name}" ${message}`);
  process.exit(1);
}

const indent = (lines, pad) => lines.map((l) => pad + l).join("\n");

writeFileSync(
  OUT,
  `/* GENERATED by scripts/build-tokens.mjs from tokens/tokens.json. Do not edit. */

@theme {
  /* Tailwind's stock palette, type scale and radii are cleared so the only
     colours, sizes and radii on the site are the ones in tokens.json. */
  --color-*: initial;
  --text-*: initial;
  --radius-*: initial;

${indent(theme, "  ")}
}

:root {
${indent(plain, "  ")}
}

@media (prefers-color-scheme: dark) {
  :root {
${indent(dark, "    ")}
  }
}
`,
);

console.log(
  `tokens: ${theme.length + plain.length} properties (${dark.length} with a dark value) -> app/tokens.css`,
);
