#!/usr/bin/env node
/**
 * sync-content.mjs — build-time sync from published Google Sheets tabs to
 * generated JSON under src/data/generated/.
 *
 * The site has no backend and no runtime fetching: every byte of content is
 * bundled at build time. So "managed in Google Sheets" means "a scheduled job
 * pulls the sheet, writes JSON into the repo, and commits it". This script is
 * that job.
 *
 * Usage:
 *   node scripts/sync-content.mjs                 # sync every configured tab
 *   node scripts/sync-content.mjs --tab education # sync one tab (repeatable)
 *   node scripts/sync-content.mjs --check         # exit 1 if output would change
 *   node scripts/sync-content.mjs --config path   # use an alternate config file
 *
 * Exit codes: 0 = success (or --check found no drift), 1 = network, config,
 * validation, or drift failure. Writes are atomic across the whole run: if any
 * tab fails, nothing is written.
 *
 * See docs/content-sheet.md for the sheet + config contract.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import Papa from "papaparse";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_CONFIG = "content.config.json";
const DEFAULT_OUT_DIR = "src/data/generated";
const GENERATED_NOTICE =
  "Auto-generated by scripts/sync-content.mjs from a published Google Sheet. Do not edit by hand.";
const FETCH_TIMEOUT_MS = 30_000;
const FETCH_ATTEMPTS = 3;
const MAX_REPORTED_ERRORS = 25;

const HELP = `sync-content — Google Sheets -> src/data/generated/*.json

  --tab <key>       Sync only this tab (repeatable). Default: every tab.
  --check           Report drift and exit 1 instead of writing.
  --config <path>   Config file (default: ${DEFAULT_CONFIG}).
  -h, --help        Show this help.
`;

/* ------------------------------------------------------------------ *
 * Column type coercion
 * ------------------------------------------------------------------ */

const TRUEISH = new Set(["true", "yes", "y", "1", "x", "✓"]);
const FALSEISH = new Set(["false", "no", "n", "0", ""]);

const COERCERS = {
  string: (raw) => raw,
  number: (raw) => {
    if (raw === "") return null;
    // Strip commas only in unambiguous thousands-separator position. Blanket
    // stripping would turn a fr-CA decimal like "3,5" into 35 — silent
    // corruption, where a hard failure is what we want.
    const text = /^[+-]?\d{1,3}(,\d{3})+(\.\d+)?$/.test(raw) ? raw.replace(/,/g, "") : raw;
    const n = Number(text);
    if (!Number.isFinite(n)) throw new Error(`expected a number, got "${raw}"`);
    return n;
  },
  boolean: (raw) => {
    const v = raw.toLowerCase();
    if (TRUEISH.has(v)) return true;
    if (FALSEISH.has(v)) return false;
    throw new Error(`expected a boolean (true/false/yes/no/1/0), got "${raw}"`);
  },
  "string-array": (raw) =>
    raw
      .split("|")
      .map((part) => part.trim())
      .filter((part) => part !== ""),
};

const TYPE_ALIASES = {
  text: "string",
  str: "string",
  int: "number",
  integer: "number",
  float: "number",
  bool: "boolean",
  list: "string-array",
  array: "string-array",
};

const KNOWN_TYPES = Object.keys(COERCERS);

function resolveType(declared) {
  const name = String(declared).toLowerCase();
  return TYPE_ALIASES[name] ?? name;
}

/* ------------------------------------------------------------------ *
 * Errors
 * ------------------------------------------------------------------ */

/** Failure the user can act on — reported without a stack trace. */
class SyncError extends Error {
  constructor(message) {
    super(message);
    this.name = "SyncError";
  }
}

function fail(message) {
  throw new SyncError(message);
}

/** Repo-relative path when the file lives in the repo, absolute otherwise. */
function displayPath(absolute) {
  const relative = path.relative(REPO_ROOT, absolute);
  return relative.startsWith("..") ? absolute : relative;
}

function formatList(items) {
  const shown = items.slice(0, MAX_REPORTED_ERRORS);
  const rest = items.length - shown.length;
  const lines = shown.map((item) => `  - ${item}`);
  if (rest > 0) lines.push(`  - ...and ${rest} more`);
  return lines.join("\n");
}

/* ------------------------------------------------------------------ *
 * Config
 * ------------------------------------------------------------------ */

async function loadConfig(configPath) {
  const absolute = path.resolve(REPO_ROOT, configPath);
  if (!existsSync(absolute)) fail(`Config file not found: ${absolute}`);

  let parsed;
  try {
    parsed = JSON.parse(await readFile(absolute, "utf8"));
  } catch (error) {
    fail(`Config file ${configPath} is not valid JSON: ${error.message}`);
  }

  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed)) {
    fail(`Config file ${configPath} must contain a JSON object.`);
  }
  if (!Array.isArray(parsed.tabs)) {
    fail(`Config file ${configPath} must have a "tabs" array.`);
  }

  const outDir = parsed.outDir ?? DEFAULT_OUT_DIR;
  const seenKeys = new Set();
  const seenOutputs = new Set();

  for (const tab of parsed.tabs) {
    const label = tab?.key ? `tab "${tab.key}"` : `tab #${parsed.tabs.indexOf(tab) + 1}`;

    if (!tab || typeof tab !== "object") fail(`Config ${label}: expected an object.`);
    for (const field of ["key", "csvUrl", "output"]) {
      if (typeof tab[field] !== "string" || tab[field].trim() === "") {
        fail(`Config ${label}: missing required field "${field}".`);
      }
    }
    if (seenKeys.has(tab.key)) fail(`Config: duplicate tab key "${tab.key}".`);
    seenKeys.add(tab.key);

    if (tab.output.includes("/") || tab.output.includes("\\") || tab.output.includes("..")) {
      fail(`Config ${label}: "output" must be a bare filename inside ${outDir}, got "${tab.output}".`);
    }
    if (!tab.output.endsWith(".json")) {
      fail(`Config ${label}: "output" must end in .json, got "${tab.output}".`);
    }
    if (seenOutputs.has(tab.output)) fail(`Config: duplicate output file "${tab.output}".`);
    seenOutputs.add(tab.output);

    if (tab.requiredColumns !== undefined && !Array.isArray(tab.requiredColumns)) {
      fail(`Config ${label}: "requiredColumns" must be an array of column names.`);
    }
    if (tab.ignoreColumns !== undefined && !Array.isArray(tab.ignoreColumns)) {
      fail(`Config ${label}: "ignoreColumns" must be an array of column names.`);
    }
    for (const [column, declared] of Object.entries(tab.columns ?? {})) {
      const type = resolveType(declared);
      if (!KNOWN_TYPES.includes(type)) {
        fail(
          `Config ${label}: column "${column}" declares unknown type "${declared}". ` +
            `Known types: ${KNOWN_TYPES.join(", ")}.`,
        );
      }
    }
    if (tab.sortDirection !== undefined && !["asc", "desc"].includes(tab.sortDirection)) {
      fail(`Config ${label}: "sortDirection" must be "asc" or "desc".`);
    }
    // A column dropped by ignoreColumns is gone from the row objects before
    // sorting, grouping, and the required-cell check run — so listing it in
    // both places would silently disable whichever feature referenced it.
    const ignored = new Set(tab.ignoreColumns ?? []);
    const conflicts = [
      [tab.sortBy, "sortBy"],
      [tab.groupBy?.column, "groupBy.column"],
      ...(tab.requiredColumns ?? []).map((column) => [column, "requiredColumns"]),
    ];
    for (const [column, where] of conflicts) {
      if (typeof column === "string" && ignored.has(column)) {
        fail(`Config ${label}: "${where}" column "${column}" is also listed in ignoreColumns.`);
      }
    }
    if (tab.groupBy !== undefined) {
      if (typeof tab.groupBy?.column !== "string") {
        fail(`Config ${label}: "groupBy" must be an object with a "column" string.`);
      }
      const references = tab.groupBy.references;
      if (references !== undefined) {
        if (typeof references?.tab !== "string" || typeof references?.column !== "string") {
          fail(`Config ${label}: "groupBy.references" needs both "tab" and "column" strings.`);
        }
        if (!parsed.tabs.some((other) => other?.key === references.tab)) {
          fail(`Config ${label}: "groupBy.references.tab" points at unknown tab "${references.tab}".`);
        }
      }
    }
  }

  return { ...parsed, outDir, tabs: parsed.tabs };
}

/* ------------------------------------------------------------------ *
 * Fetch + parse
 * ------------------------------------------------------------------ */

async function fetchCsv(tab) {
  let lastError;
  for (let attempt = 1; attempt <= FETCH_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetch(tab.csvUrl, {
        redirect: "follow",
        signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
        headers: { accept: "text/csv,*/*" },
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status} ${response.statusText}`);
      }
      const contentType = response.headers.get("content-type") ?? "";
      const body = await response.text();
      if (contentType.includes("text/html") || /^\s*<(!doctype|html)/i.test(body)) {
        fail(
          `Tab "${tab.key}": the URL returned HTML, not CSV.\n` +
            `  URL: ${tab.csvUrl}\n` +
            `  The tab must be published via File -> Share -> Publish to web (that tab, CSV), ` +
            `and the URL must end in output=csv.`,
        );
      }
      return body;
    } catch (error) {
      if (error instanceof SyncError) throw error;
      lastError = error;
      if (attempt < FETCH_ATTEMPTS) {
        await new Promise((resolve) => setTimeout(resolve, 500 * attempt));
      }
    }
  }
  fail(`Tab "${tab.key}": failed to fetch ${tab.csvUrl} after ${FETCH_ATTEMPTS} attempts — ${lastError?.message ?? lastError}`);
}

const isBlank = (cells) => !cells.some((cell) => String(cell ?? "").trim() !== "");

/**
 * Parses to arrays-of-arrays rather than papaparse's `header: true` mode, for
 * two reasons: header mode silently renames duplicate columns to `name_1`
 * (leaking a bogus field into the JSON instead of failing), and it discards the
 * line numbers needed to point the author at the right sheet row.
 */
function parseCsv(tab, csvText) {
  const text = csvText.replace(/^\uFEFF/, ""); // strip UTF-8 BOM

  // Explicit comma: the source is always a `output=csv` export, and papaparse's
  // delimiter auto-detection gets confused by blank rows.
  const result = Papa.parse(text, { delimiter: ",", skipEmptyLines: false });

  const fatal = (result.errors ?? []).filter((error) => error.type === "Quotes");
  if (fatal.length > 0) {
    fail(
      `Tab "${tab.key}": CSV could not be parsed.\n` +
        formatList(
          fatal.map((error) => `row ${error.row === undefined ? "?" : error.row + 1}: ${error.message}`),
        ),
    );
  }

  const table = result.data.map((cells) => (Array.isArray(cells) ? cells : []));

  // The header is the first row with any content — a leading blank row is easy
  // to create in Sheets and shouldn't be a hard failure.
  const headerIndex = table.findIndex((cells) => !isBlank(cells));
  if (headerIndex === -1) {
    fail(`Tab "${tab.key}": CSV is empty. The first non-blank row of the tab must be column names.`);
  }

  const headerCells = table[headerIndex].map((cell) => String(cell ?? "").trim());
  const headers = headerCells.filter((header) => header !== "");

  const duplicates = headers.filter((header, index) => headers.indexOf(header) !== index);
  if (duplicates.length > 0) {
    fail(
      `Tab "${tab.key}": duplicate column name(s) in the header row: ${[...new Set(duplicates)].join(", ")}. ` +
        `Column names must be unique.`,
    );
  }

  // Column name -> position within each row array. Unnamed columns are dropped.
  const columnIndex = new Map();
  headerCells.forEach((header, index) => {
    if (header !== "") columnIndex.set(header, index);
  });

  const rows = [];
  const overflow = [];

  for (let index = headerIndex + 1; index < table.length; index += 1) {
    const cells = table[index];
    if (isBlank(cells)) continue;

    // Sheet rows are 1-based and counted before blank rows are dropped, so this
    // is the row number the author actually sees in Google Sheets.
    const sheetRow = index + 1;

    const past = cells.slice(headerCells.length).filter((cell) => String(cell ?? "").trim() !== "");
    if (past.length > 0) {
      overflow.push(`row ${sheetRow}: ${past.length} value(s) sit past the last named column`);
    }

    rows.push({ sheetRow, cells });
  }

  if (overflow.length > 0) {
    fail(
      `Tab "${tab.key}": data found outside the header columns — those cells would be silently dropped.\n` +
        formatList(overflow) +
        `\n  Add a header for those columns, or clear the stray cells.`,
    );
  }

  return { headers, columnIndex, rows };
}

/* ------------------------------------------------------------------ *
 * Validate + coerce
 * ------------------------------------------------------------------ */

function assertConfiguredColumnsExist(tab, headers) {
  const referenced = new Map();
  const note = (column, where) => {
    if (typeof column === "string" && column !== "") referenced.set(column, where);
  };

  for (const column of tab.requiredColumns ?? []) note(column, "requiredColumns");
  for (const column of Object.keys(tab.columns ?? {})) note(column, "columns");
  for (const column of tab.ignoreColumns ?? []) note(column, "ignoreColumns");
  note(tab.sortBy, "sortBy");
  note(tab.groupBy?.column, "groupBy.column");

  const missing = [...referenced.entries()]
    .filter(([column]) => !headers.includes(column))
    .map(([column, where]) => `"${column}" (from ${where})`);

  if (missing.length > 0) {
    fail(
      `Tab "${tab.key}": config references column(s) that are not in the sheet:\n` +
        formatList(missing) +
        `\n  Columns found in the sheet: ${headers.join(", ")}`,
    );
  }
}

function assertRequiredColumns(tab, headers) {
  const missing = (tab.requiredColumns ?? []).filter((column) => !headers.includes(column));
  if (missing.length > 0) {
    fail(
      `Tab "${tab.key}": missing required column(s): ${missing.join(", ")}.\n` +
        `  Columns found in the sheet: ${headers.join(", ")}\n` +
        `  Add the column to the sheet tab (or drop it from requiredColumns in the config).`,
    );
  }
}

function buildRows(tab, headers, columnIndex, rawRows) {
  const ignored = new Set(tab.ignoreColumns ?? []);
  // Keys are emitted in alphabetical order so the JSON stays canonical even if
  // someone reorders columns in the sheet.
  const kept = headers.filter((header) => !ignored.has(header)).sort();
  const required = new Set(tab.requiredColumns ?? []);
  const types = Object.fromEntries(
    Object.entries(tab.columns ?? {}).map(([column, declared]) => [column, resolveType(declared)]),
  );

  const errors = [];
  const rows = [];

  for (const { sheetRow, cells } of rawRows) {
    const row = {};

    for (const column of kept) {
      const raw = String(cells[columnIndex.get(column)] ?? "").trim();

      if (required.has(column) && raw === "") {
        errors.push(`row ${sheetRow}: required column "${column}" is empty`);
        continue;
      }

      const coerce = COERCERS[types[column] ?? "string"];
      try {
        row[column] = coerce(raw);
      } catch (error) {
        errors.push(`row ${sheetRow}, column "${column}": ${error.message}`);
      }
    }

    rows.push(row);
  }

  if (errors.length > 0) {
    fail(`Tab "${tab.key}": ${errors.length} invalid cell(s).\n` + formatList(errors));
  }

  return { rows, kept };
}

/** `kept`, not the raw header list: an ignored column is gone from the rows. */
function sortRows(tab, kept, rows) {
  const sortBy = tab.sortBy ?? (kept.includes("order") ? "order" : null);
  if (!sortBy) return { rows, sortBy: null };

  const direction = tab.sortDirection === "desc" ? -1 : 1;
  // Array#sort is stable, so equal keys keep sheet order.
  const sorted = [...rows].sort((a, b) => {
    const left = a[sortBy];
    const right = b[sortBy];
    if (left === right) return 0;
    if (left === null || left === undefined) return 1;
    if (right === null || right === undefined) return -1;
    if (typeof left === "number" && typeof right === "number") {
      return (left - right) * direction;
    }
    // Code-unit comparison, not localeCompare: locale collation varies by
    // machine and would make output non-deterministic across environments.
    return (String(left) < String(right) ? -1 : 1) * direction;
  });

  return { rows: sorted, sortBy };
}

/* ------------------------------------------------------------------ *
 * Serialize
 * ------------------------------------------------------------------ */

function serialize(tab, rows, sortBy) {
  const document = {
    $generated: GENERATED_NOTICE,
    tab: tab.key,
    source: tab.csvUrl,
    // Deliberately no timestamp: a changing field would defeat the zero-diff
    // guarantee the CI commit step relies on.
    sortedBy: sortBy,
    count: rows.length,
  };

  if (tab.groupBy) {
    const groups = {};
    for (const row of rows) {
      const key = String(row[tab.groupBy.column] ?? "");
      (groups[key] ??= []).push(row);
    }
    document.groupedBy = tab.groupBy.column;
    document.groups = Object.fromEntries(Object.keys(groups).sort().map((key) => [key, groups[key]]));
  } else {
    document.rows = rows;
  }

  return `${JSON.stringify(document, null, 2)}\n`;
}

/* ------------------------------------------------------------------ *
 * Cross-tab referential integrity
 * ------------------------------------------------------------------ */

function checkReferences(results) {
  const byKey = new Map(results.map((result) => [result.tab.key, result]));
  const errors = [];

  for (const { tab, rows } of results) {
    const references = tab.groupBy?.references;
    if (!references) continue;

    const parent = byKey.get(references.tab);
    if (!parent) {
      console.warn(
        `  note: skipping foreign-key check for "${tab.key}" — parent tab "${references.tab}" was not part of this run.`,
      );
      continue;
    }

    // Catch a typo'd references.column up front — otherwise every child value
    // looks orphaned and the error points at the wrong thing.
    if (parent.rows.length > 0 && !(references.column in parent.rows[0])) {
      errors.push(
        `Tab "${tab.key}": "groupBy.references.column" is "${references.column}", ` +
          `but tab "${references.tab}" has no such column. ` +
          `Its columns are: ${Object.keys(parent.rows[0]).join(", ")}.`,
      );
      continue;
    }

    const parentValues = new Set(parent.rows.map((row) => String(row[references.column] ?? "")));
    const unknown = new Set(
      rows
        .map((row) => String(row[tab.groupBy.column] ?? ""))
        .filter((value) => !parentValues.has(value)),
    );

    if (unknown.size > 0) {
      errors.push(
        `Tab "${tab.key}": column "${tab.groupBy.column}" references ` +
          `"${references.tab}"."${references.column}", but these values have no matching parent row:\n` +
          formatList([...unknown].sort()),
      );
    }
  }

  if (errors.length > 0) fail(errors.join("\n"));
}

/* ------------------------------------------------------------------ *
 * Run
 * ------------------------------------------------------------------ */

async function syncTab(tab) {
  process.stdout.write(`  ${tab.key} ... `);
  const csvText = await fetchCsv(tab);
  const { headers, columnIndex, rows: rawRows } = parseCsv(tab, csvText);

  assertRequiredColumns(tab, headers);
  assertConfiguredColumnsExist(tab, headers);

  const { rows: coerced, kept } = buildRows(tab, headers, columnIndex, rawRows);
  const { rows, sortBy } = sortRows(tab, kept, coerced);

  process.stdout.write(`${rows.length} row(s)${sortBy ? ` sorted by "${sortBy}"` : ""}\n`);
  if (!sortBy) {
    console.warn(
      `  note: tab "${tab.key}" has no sort column, so JSON order mirrors sheet row order. ` +
        `Add an "order" integer column (or set "sortBy") to make ordering explicit.`,
    );
  }

  return { tab, rows, sortBy };
}

async function main() {
  let values;
  try {
    ({ values } = parseArgs({
      options: {
        check: { type: "boolean", default: false },
        tab: { type: "string", multiple: true },
        config: { type: "string", default: DEFAULT_CONFIG },
        help: { type: "boolean", short: "h", default: false },
      },
    }));
  } catch (error) {
    fail(`${error.message}\n\n${HELP}`);
  }

  if (values.help) {
    process.stdout.write(HELP);
    return;
  }

  const config = await loadConfig(values.config);

  let tabs = config.tabs;
  if (values.tab?.length) {
    const known = new Set(tabs.map((tab) => tab.key));
    const unknown = values.tab.filter((key) => !known.has(key));
    if (unknown.length > 0) {
      fail(
        `Unknown --tab value(s): ${unknown.join(", ")}.\n` +
          `  Tabs in ${values.config}: ${[...known].join(", ") || "(none)"}`,
      );
    }
    tabs = tabs.filter((tab) => values.tab.includes(tab.key));
  }

  if (tabs.length === 0) {
    console.log(
      `No tabs configured in ${values.config} — nothing to sync. ` +
        `Add an entry to "tabs" (see docs/content-sheet.md).`,
    );
    return;
  }

  console.log(`${values.check ? "Checking" : "Syncing"} ${tabs.length} tab(s) from ${values.config}:`);

  // Phase 1: fetch + validate everything before touching disk, so a failure
  // part-way through never leaves src/data/generated/ half-updated.
  const results = [];
  for (const tab of tabs) {
    results.push(await syncTab(tab));
  }
  checkReferences(results);

  // Phase 2: write (or, under --check, compare).
  const outDir = path.resolve(REPO_ROOT, config.outDir);
  if (!values.check) await mkdir(outDir, { recursive: true });

  const drifted = [];
  const written = [];

  for (const { tab, rows, sortBy } of results) {
    const outPath = path.join(outDir, tab.output);
    const next = serialize(tab, rows, sortBy);
    const current = existsSync(outPath) ? await readFile(outPath, "utf8") : null;
    const relative = displayPath(outPath);

    if (current === next) continue;

    if (values.check) {
      drifted.push(`${relative} (${current === null ? "missing" : "out of date"})`);
    } else {
      await writeFile(outPath, next, "utf8");
      written.push(relative);
    }
  }

  if (values.check) {
    if (drifted.length > 0) {
      fail(
        `Generated content is out of date:\n` +
          formatList(drifted) +
          `\n  Run "npm run sync-content" and commit the result.`,
      );
    }
    console.log("Generated content is up to date.");
    return;
  }

  if (written.length === 0) {
    console.log("No changes — generated content already up to date.");
  } else {
    console.log(`Wrote ${written.length} file(s):`);
    console.log(formatList(written));
  }
}

try {
  await main();
} catch (error) {
  if (error instanceof SyncError) {
    console.error(`\nsync-content failed:\n${error.message}`);
  } else {
    console.error(`\nsync-content failed with an unexpected error:`);
    console.error(error);
  }
  process.exitCode = 1;
}
